//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Server;

public class Music implements java.lang.Cloneable,
                              java.io.Serializable
{
    public int identifier;

    public String titre;

    public String artiste;

    public String album;

    public String path;

    public Music()
    {
        this.titre = "";
        this.artiste = "";
        this.album = "";
        this.path = "";
    }

    public Music(int identifier, String titre, String artiste, String album, String path)
    {
        this.identifier = identifier;
        this.titre = titre;
        this.artiste = artiste;
        this.album = album;
        this.path = path;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Music r = null;
        if(rhs instanceof Music)
        {
            r = (Music)rhs;
        }

        if(r != null)
        {
            if(this.identifier != r.identifier)
            {
                return false;
            }
            if(this.titre != r.titre)
            {
                if(this.titre == null || r.titre == null || !this.titre.equals(r.titre))
                {
                    return false;
                }
            }
            if(this.artiste != r.artiste)
            {
                if(this.artiste == null || r.artiste == null || !this.artiste.equals(r.artiste))
                {
                    return false;
                }
            }
            if(this.album != r.album)
            {
                if(this.album == null || r.album == null || !this.album.equals(r.album))
                {
                    return false;
                }
            }
            if(this.path != r.path)
            {
                if(this.path == null || r.path == null || !this.path.equals(r.path))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Server::Music");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, identifier);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, titre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, artiste);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, album);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, path);
        return h_;
    }

    public Music clone()
    {
        Music c = null;
        try
        {
            c = (Music)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.identifier);
        ostr.writeString(this.titre);
        ostr.writeString(this.artiste);
        ostr.writeString(this.album);
        ostr.writeString(this.path);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.identifier = istr.readInt();
        this.titre = istr.readString();
        this.artiste = istr.readString();
        this.album = istr.readString();
        this.path = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Music v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Music ice_read(com.zeroc.Ice.InputStream istr)
    {
        Music v = new Music();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Music> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Music v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Music> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Music.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Music _nullMarshalValue = new Music();

    /** @hidden */
    public static final long serialVersionUID = 2954881375382716259L;
}
